project:
  type: default

format:
  pdf:
    documentclass: article
    toc: true
    number-sections: true
    papersize: letter
    geometry:
      - margin=2.5cm
    lang: es

execute:
  echo: false
  warning: false
  freeze: auto
